export interface IMovie {
    title: string;
    year: string,
    rated: string,
    released: string,
    runtime: string,
    genre: string,
    director: string,
    writer: string,
    actors: string,
    plot: string,
    language: string,
    country: string,
    awards: string,
    poster: string,
    ratings: any[],
    metascore: string,
    imdbRating: string,
    imdbVotes: string,
    dvd: string,
    boxOffice: string,
    production: string,
    website: string,
    imdbID: string;
  }